### PR TITLE
compile-time specification of scalar type

### PR DESCRIPTION
**Pull request by benman1**
Hi!
Well done creating this library. It looks fantastic! 

This is a rather minor change. It adds a compilation flag for the Scalar type (-DMDNN_SCALAR). I thought that would be more convenient than changing/patching the config.h file. I've made a few more changes down the line so the types would be Scalar rather than double. 

In order to test this with float types (-DMDNN_SCALAR=float), I've changed the type definitions in the example.cpp as follows:

```
...
using namespace MiniDNN;

typedef Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic>  Matrix;
typedef Eigen::Vector<float, Eigen::Dynamic> Vector;
...

```

Thanks!
Ben.

### CODE REVIEW

**Comment by giovastabile** [comment]
@benman1 Thanks for the patch!! In my opinion, we can merge this but I will let @yixuan to have a look as well and to close it.

**Comment by yixuan** [comment]
Good point. I like this change. Thank you @benman1!

**Comment by yixuan** [comment]
Sorry, wrong click last time. Now it has been merged.

**Comment by benman1** [comment]
Nice to see. Thank you!

----

**Pull request merged**
